/// An infinite sequence of values generated by the provided `generator` closure
public struct InfiniteSequence<Element>: Sequence, IteratorProtocol {
    let generator: () -> Element
    /// Returns: The next element in this sequence
    public mutating func next() -> Element? {
        generator()
    }
}
