name: Docc

on:
  push:
    branches: [ main ]

jobs:
  update-docs:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Compile Docs
      run: |
        set -eux
        git config user.email "nicorichard@users.noreply.github.com"
        git config user.name "Nico Richard"
        git fetch
        git worktree add --checkout gh-pages origin/gh-pages        
        export SWIFTPM_ENABLE_COMMAND_PLUGINS=1 
        swift package \
          --allow-writing-to-directory gh-pages/docs \
          generate-documentation \
          --target Genything \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path Genything \
          --output-path gh-pages/docs
        CURRENT_COMMIT_HASH=`git rev-parse --short HEAD`
        cd gh-pages
        git add docs
        if [ -n "$(git status --porcelain)" ]; then
            echo "Documentation changes found. Commiting the changes to the 'gh-pages' branch and pushing to origin."
            git commit -m "Update GitHub Pages documentation site to '$CURRENT_COMMIT_HASH'."
            git push
        else
          echo "No documentation changes."
        fi