name: Docc

on:
  push:
    branches: [ main ]

jobs:
  update-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
    - name: Compile Docs
      run: |
        set -eux
        git config user.email "nicorichard@users.noreply.github.com"
        git config user.name "Nico Richard"
        export DOCC_JSON_PRETTYPRINT="YES"
        export SWIFTPM_ENABLE_COMMAND_PLUGINS=1 
        swift package \
          --allow-writing-to-directory docs \
          generate-documentation \
          --target Genything \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path Genything \
          --output-path docs
        CURRENT_COMMIT_HASH=`git rev-parse --short HEAD`
        git add docs
        if [ -n "$(git status --porcelain)" ]; then
            echo "Documentation changes found. Commiting and pushing to origin."
            git commit -m "Update ./docs to '$CURRENT_COMMIT_HASH'."
            git push
        else
          echo "No documentation changes."
        fi